### ISSUE TITLE
Content View when editing a complex item is limited ot only 25 items.

### ISSUE THREAD

**Issue by sonjamichelle** [HalcyonGrid/halcyon#82] opened 2019-04-27 12:36 UTC
Not sure if this is a server issue or viewer issue. I'm reporting and receiving this issue as a man in the middle. 'Nother words, I didn't find the issue but I'm being told about it and trying to relay to the best of my understanding.

Anyhow, when you open a complex object that has lot's of animations, scripts, notecards, etc. you can only view the first 25 items or so in the content pane of the Edit Dialog. Anything beyond that is hidden. The only work around is to move items a few at a time into your inventory until the hidden items are revealed.

I've added a screenie of what I'm being told.

![Inventory_Issue](https://user-images.githubusercontent.com/8279771/56849799-f3827980-68be-11e9-90a1-c8b7f7091ccb.png)

I'm being told, If I understand her correctly, that it also occurs in other viewers. Hence why I'm posting on the server side first.

**Comment by kf6kjg** [comment] 2019-04-28 03:22
Duplicate of #81?

**Comment by zauberparacelsus** [comment] 2019-04-28 15:40
Yes, it's a duplicate of #71

**Closed** 2019-04-28 15:41 UTC
Labels: duplicate
