### ISSUE TITLE
Z axes and Sim Owners - discovered in Opensim

### ISSUE THREAD

**Issue by Ana-Green** [HalcyonGrid/halcyon#73] opened 2019-03-06 10:55 UTC
Hello everyone,

If a normal user in Halcyon teleports on any way he or she will land on the correct XYZ, this is the same on Opensim, however as soon the Sim Owner changes his  level (on Opensim)  to Level 200 God Mode he or she will always arrive underwater  Z =0 or Z = 2, if switching  back to level 0 (Leaving God Mode) the Sim Owner can just Teleport as every other user. Halcyon the Grid Owner will regardless or he or she leaves or enters Level 200 always arrive underwater  Z =0 or Z = 2, related?       

Best regards, 
Ana Green

**Comment by emperorstarfinder** [comment] 2019-03-06 11:41
Ana,  

This is the same issue as issue https://github.com/HalcyonGrid/halcyon/issues/61

The fix for this is when setting the landing point in the parcel options tab make sure to set the routing to Landing Point.  That will fix that issue.  It actually contrary to what some may think actually has nothing to do with the GodLevel, Region owner, Estate Manager, etc.  It is simply that the routing is believed to be set to Anywhere by the grid and region services.  The same is true with OpenSim.

**Comment by Ana-Green** [comment] 2019-03-06 12:57
Its duplicated in a fly set Opensim up (local) on a stick is fine, upload some OAR on both, so you are the owner from that sim create a second region lets say in meters 4000,4000 and region 2, 4040,4000 now  Tp up and down landings point set. Now set on the 4000,4000 regions your level to GodMode and try to tp again you'll notice that you'll end up at Z = 0 or 2 that sounds a lot to the same as with Halcyon to me.

**Comment by emperorstarfinder** [comment] 2019-03-06 13:37
Yes set the routing in the options tab in Parcel details to "Landing Point" and that will fix landing at the wrong place from a teleport and will fix the issue with landing under water from last login as well.  

The problem is by default the routing for landing at the destination on your parcel has a routing setting by default set to "Anywhere".  The Routing setting does not change automatically when you set it to the landing point.

**Comment by kf6kjg** [comment] 2019-03-10 21:57
This issue appears to be an OpenSim issue at best, a non-issue at worst. Thus far I've not tested much in the way of Grid/Estate/Parcel owners or grid admin mode effects, but I do know that Halcyon does have customized code in that area.  Cosing until such time as any actual issue is found in Halcyon.

**Closed by kf6kjg** 2019-03-10 21:57 UTC
