### ISSUE TITLE
Economy. Can't pay another avatar. Can't pay for Classifieds. Seems that economy_totals is not being updated.

### ISSUE THREAD

**Issue by sonjamichelle** [HalcyonGrid/halcyon#78] opened 2019-04-07 20:54 UTC
I'm trying to get an economy working on the grid. Running master branch pulled from about a week ago.

I try to pay another avatar nothing happens. In the DB the transaction is listed in economy_transaction but the new balances aren't reflected in economy_totals.

I tried paying for a Classified, not sure where the cost is specified. When I went through the process an error showed up in the region console. Log is attached.

[Halcyon.log.txt](https://github.com/HalcyonGrid/halcyon/files/3052029/Halcyon.log.txt)

I looked at \halcyon-master\OpenSim\Region\CoreModules\Avatar\Currency\AvatarCurrency.cs

Nothing really stood out other than the lack of entries for the table economy_totals.

**Comment by sonjamichelle** [comment] 2019-04-07 21:38
I manually entered the balances in economy_totals to reflect the changes in economy_transaction.

Tried to buy land that was set for sale. The viewer crashes out upon pressing buy land in either the pie menu or about land dialog.

Here is my firestorm log.

[Firestorm.log.txt](https://github.com/HalcyonGrid/halcyon/files/3052043/Firestorm.log.txt)

In singularity I get There has been an error while fetching land buying information.

**Comment by sonjamichelle** [comment] 2019-04-07 22:05
Ok, I restarted my PC, replaced the LandTool.aspx and LandTool.aspx.vb from website source, redid my IIS rewrite rule to redirect from LandTool.php. 

Firestorm works again. No crashing able to sell/buy land. Payment issue still exists.

Singularity gives **There has been an error while fetching land buying information. Send failed since rewinding of the data stream failed.**

**Comment by emperorstarfinder** [comment] 2019-04-07 22:09
Singularity Viewer has been updated in a very infrequent way.  So it might not be good to test against Singularity Viewer.  I would suggest either Alchemy, Cool VL Viewer (which is also using the same code as Singularity is based on), or maybe even Kokua viewer.

**Comment by kf6kjg** [comment] 2019-04-07 22:12
The rewinding error, based on some quick Google fu, seems to indicate something's not right with the redirect.  Possibly a HTTP method type change - e.g. from GET to POST or vice verse.

I've marked this working as intended as the problems here are about external services related to Halcyon, not Halcyon itself.  If you agree, please close the issue.

**Comment by emperorstarfinder** [comment] 2019-04-07 22:14
As a post thought that I had after I posted my previous response, my team ran into this on our Halcyon test bed and managed to fix it and get it working with Singularity.  I will look at my notes and see what we did.  Though this likely is an external issue and not in the core.

**Comment by sonjamichelle** [comment] 2019-04-07 22:21
Rundown:

Firestorm
Land buy/sell for $0 works
Land buy/sell for $amount works but NO funds are exchanged. Something is wrong with payment transaction. Transaction recorded in economy_transaction but to balance recorded in economy_totals

Singularity
Land buy/sell not working period.

**Comment by kf6kjg** [comment] 2019-04-07 22:29
Since it appears that you are using Vinhold's tooling for the economy I recommend chatting with him to see if there's something wrong. I don't want to sound dismissive. However since land transactions go through external tooling, such as Vinhold's tooling, and are/were working in other grids such as InWorldz/IZ, Vin's grids, etc., this isn't feeling like an actual issue with Halcyon itself.

**Comment by sonjamichelle** [comment] 2019-04-07 22:32
It's not just land, it is ANY payments that are failing. The transactions are being recorded in economy_transactions but no balances are being recorded in economy_totals.

MY conversation with @Vinhold and exchange of information kinda dead ended. Not sure if he got called away or if he was looking deeper.

**Comment by sonjamichelle** [comment] 2019-04-07 22:37
Just tried to create a box, set it for sale. My wife was able to buy it, payment messages were issued, objects were exchanged. But NO money was exchanged in the DB.

**Comment by kf6kjg** [comment] 2019-04-07 22:59
That's a bit concerning. What version of Halcyon are you using?

**Comment by sonjamichelle** [comment] 2019-04-07 23:36
Turns out to be a missing TRIGGER in the DB

@Vinhold came up with this.

`
DELIMITER $$
CREATE DEFINER=root@localhost TRIGGER mydata.upd_total_on_new_trans
AFTER INSERT ON mydata.economy_transaction -- This line shows as a syntax error.
FOR EACH ROW
BEGIN
  IF (SELECT COUNT(*) FROM economy_totals WHERE user_id = NEW.destAvatarId) = 0 THEN
  INSERT IGNORE INTO economy_totals SELECT NEW.destAvatarId, SUM(transactionAmount) FROM economy_transaction WHERE destAvatarID = NEW.destAvatarId;
  ELSE
  UPDATE economy_totals SET total = total + NEW.transactionAmount WHERE user_id = NEW.destAvatarId;
  END IF;
END$$
DELIMITER ;
`
Of course changing the db name where needed.

Payments process properly now.

**Comment by sonjamichelle** [comment] 2019-04-08 01:35
It appears the problem is on line 338 of /bin/halcyon-core-base.sql 

`DELIMITER ;;
/*!50003 CREATE*/ /*!50003 TRIGGER `upd_total_on_new_trans`
AFTER INSERT ON `economy_transaction`
FOR EACH ROW
BEGIN
  IF (SELECT COUNT(*) FROM economy_totals WHERE user_id = NEW.destAvatarId) = 0 THEN
		INSERT IGNORE INTO economy_totals SELECT NEW.destAvatarId, SUM(transactionAmount) FROM economy_transaction WHERE destAvatarID = NEW.destAvatarId;
  ELSE
		UPDATE economy_totals SET total = total + NEW.transactionAmount WHERE user_id = NEW.destAvatarId;
  END IF;
END */;;
DELIMITER `

Too many comment tags blocking the creation of the trigger?

**Comment by sonjamichelle** [comment] 2019-04-08 06:37
> 
> 
> That's a bit concerning. What version of Halcyon are you using?

I'm using 0.9.41.7201  Use the GitHub zip download about a week ago.

**Comment by sonjamichelle** [comment] 2019-04-24 13:35
I've made the changes to line 338 in /bin/halcyon-core-base.sql that should fix the issue for new grids. Pull Request #81

**Comment by kf6kjg** [comment] 2021-04-21 17:58
Closed in #81

**Closed by kf6kjg** 2021-04-21 17:58 UTC
Labels: working as intended
